/**:
  ros__parameters:
    video_device: "/dev/cam_rear"
    framerate: 30.0
    io_method: "mmap"
    frame_id: "TE2317003/usb_cam"
    pixel_format: "mjpeg"  # see usb_cam/supported_formats for list of supported formats
    image_width: 640
    image_height: 480
    camera_name: "test_camera"
    camera_info_url: "package://tetra_2dnav/config/camera_info.yaml"
    brightness: -1
    contrast: -1
    saturation: -1
    sharpness: -1
    gain: -1
    auto_white_balance: true
    white_balance: 4000
    autoexposure: true
    exposure: 100
    autofocus: false
    focus: -1