amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.1
    alpha2: 0.1
    alpha3: 0.1
    alpha4: 0.1
    alpha5: 0.1
    base_frame_id: /base_footprint
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: map
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: -0.1
    laser_min_range: -0.1
    laser_model_type: likelihood_field
    max_beams: 60
    max_particles: 3000
    min_particles: 500
    odom_frame_id: /odom
    pf_err: 0.01
    pf_z: 0.99
    recovery_alpha_fast: 0.5
    recovery_alpha_slow: 0.0001
    resample_interval: 1
    robot_model_type: differential
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: false
    transform_tolerance: 0.2
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_smooth_path_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_drive_on_heading_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_globally_updated_goal_condition_bt_node
    - nav2_is_path_valid_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_truncate_path_local_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_path_expiring_timer_condition
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_goal_updated_controller_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node
    - nav2_goal_checker_selector_bt_node
    - nav2_controller_cancel_bt_node
    - nav2_path_longer_on_approach_bt_node
    - nav2_wait_cancel_bt_node
    - nav2_spin_cancel_bt_node
    - nav2_back_up_cancel_bt_node
    - nav2_drive_on_heading_cancel_bt_node

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]
    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    # Goal checker parameters
    #precise_goal_checker:
    #  plugin: "nav2_controller::SimpleGoalChecker"
    #  xy_goal_tolerance: 0.25
    #  yaw_goal_tolerance: 0.25
    #  stateful: True
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.0174533
    # DWB parameters
    FollowPath:
      plugin: "teb_local_planner::TebLocalPlannerROS"
      odom_topic: odom
      map_frame: map
      teb_autosize: true
      dt_ref: 0.3
      dt_hysteresis: 0.03
      min_samples: 3 #5
      max_samples: 50
      global_plan_overwrite_orientation: true
      global_plan_viapoint_sep: 1.0 #0.5
      max_global_plan_lookahead_dist: 5.0
      force_reinit_new_goal_dist: 1.0
      feasibility_check_no_poses: 6 #3
      publish_feedback: false
      shrink_horizon_backup: true
      allow_init_with_backwards_motion: false #true
      exact_arc_length: false
      shrink_horizon_min_duration: 10.0
      max_vel_x: 0.8
      max_vel_y: 0.0
      max_vel_x_backwards: 0.05 #0.15
      max_vel_theta: 0.15
      acc_lim_x: 2.0
      acc_lim_y: 0.0 
      acc_lim_theta: 2.0
      min_turning_radius: 0.0
      wheelbase: 0.0
      cmd_angle_instead_rotvel: false
      footprint_model.type: line
      footprint_model.line_start: [0.0, 0.0]
      footprint_model.line_end: [-0.188, 0.0]
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.0174533
      free_goal_vel: false
      min_obstacle_dist: 0.44
      include_costmap_obstacles: true
      costmap_obstacles_behind_robot_dist: 1.5
      obstacle_poses_affected: 30
      inflation_dist: 0.5
      include_dynamic_obstacles: false
      dynamic_obstacle_inflation_dist: 0.4
      legacy_obstacle_association: false
      obstacle_association_force_inclusion_factor: 1.5
      obstacle_association_cutoff_factor: 5
      costmap_converter_plugin: ""
      costmap_converter_spin_thread: true
      costmap_converter_rate: 5.0
      no_inner_iterations: 5
      no_outer_iterations: 4
      penalty_epsilon: 0.04
      weight_max_vel_x: 1.0
      weight_max_vel_y: 0.0
      weight_max_vel_theta: 1.0
      weight_acc_lim_x: 0.0
      weight_acc_lim_y: 0.0 
      weight_acc_lim_theta: 0.0
      weight_kinematics_nh: 1000.0
      weight_kinematics_forward_drive: 1000.0
      weight_kinematics_turning_radius: 1.0
      weight_optimaltime: 1.0
      weight_obstacle: 20.0 #50.0
      weight_viapoint: 1.0
      weight_inflation: 0.1
      weight_dynamic_obstacle: 1.0
      weight_dynamic_obstacle_inflation: 1.0
      enable_homotopy_class_planning: false
      enable_multithreading: true
      simple_exploration: false
      max_number_classes: 4
      selection_cost_hysteresis: 1.0
      selection_obst_cost_scale: 1.0
      selection_viapoint_cost_scale: 1.0
      selection_alternative_time_cost: false
      roadmap_graph_no_samples: 15
      roadmap_graph_area_width: 5
      h_signature_prescaler: 0.5
      h_signature_threshold: 0.1
      obstacle_keypoint_offset: 0.1
      obstacle_heading_threshold: 0.45
      visualize_hc_graph: False
      viapoints_all_candidates: true
      switching_blocking_period: 0.0
      optimization_verbose: False
      teb_autoresize: True

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 10.0
      global_frame: odom
      robot_base_frame: base_footprint
      use_sim_time: False
      rolling_window: true
      width: 15
      height: 15
      resolution: 0.05
      robot_radius: 0.7
      plugins: ["obstacle_layer", "inflation_layer", "rgbd_obstacle_layer1", "virtual_layer2"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.58
        inflation_radius: 1.75
      obstacle_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: False
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 3
        observation_sources: laser_scan_sensor
        laser_scan_sensor:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 21.5.0
          raytrace_min_range: 0.0
          obstacle_max_range: 20.0
          obstacle_min_range: 0.0
      rgbd_obstacle_layer1:
        plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
        enabled: True
        voxel_decay: 1
        decay_model: 0
        voxel_size: 0.05
        track_unknown_space: True
        max_obstacle_height: 2.0
        unknown_threshold: 20
        mark_threshold: 3
        update_footprint_enabled: True
        combination_method: 1
        obstacle_range: 1.5
        origin_z: 0.0
        publish_voxel_map: False
        transform_tolerance: 1.0
        mapping_mode: False
        map_save_duration: 60
        observation_sources: rgbd1_mark rgbd1_clear
        rgbd1_mark:
          data_type: PointCloud2
          topic: camera2/depth/color/points
          marking: True
          clearing: False
          min_obstacle_height: 0.05
          max_obstacle_height: 2.0     # default 3, meters
          expected_update_rate: 0.0    # default 0, if not updating at this rate at least, remove from buffer
          observation_persistence: 0.0 # default 0, use all measurements taken during now-value, 0=latest
          inf_is_valid: false          # default false, for laser scans
          voxel_filter: false          # default off, apply voxel filter to sensor, recommend on
          voxel_min_points: 0          # default 0, minimum points per voxel for voxel filter
          clear_after_reading: true
        rgbd1_clear:
          data_type: PointCloud2
          topic: camera2/depth/color/points
          marking: false
          clearing: true
          max_z: 7.0                  # default 0, meters
          min_z: 0.1                  # default 10, meters
          vertical_fov_angle: 0.7  # default 0.7, radians
          horizontal_fov_angle: 1.20428 # default 1.04, radians
          decay_acceleration: 1.0     # default 0, 1/s^2. If laser scanner MUST be 0
          model_type: 0                # default 0, model type for frustum. 0=depth camera, 1=3d lidar like VLP16 or similar
      virtual_layer2:
        plugin: "virtual_costmap_layer2::VirtualLayer2"
        enabled: True
        zone_topics: virtual_costamp_layer2/zone
        obstacle_topics: virtual_costamp_layer2/obsctacles
        one_zone: False     
        forms1: [0.4, 0.0]
        forms2: [[0.4, 0.0]]
        forms3: [[-0.4, 0.0],[0.0, 0.4]]
        forms4: [[5, 5],[-5, 5],[-5, -5],[5, -5]]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 10.0
      global_frame: map
      robot_base_frame: base_footprint
      use_sim_time: False
      robot_radius: 0.7
      resolution: 0.05
      track_unknown_space: True
      plugins: ["static_layer", "obstacle_layer", "inflation_layer", "virtual_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: False
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 3
        observation_sources: laser_scan_sensor
        laser_scan_sensor:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 21.5.0
          raytrace_min_range: 0.0
          obstacle_max_range: 20.0
          obstacle_min_range: 0.0
      virtual_layer:
        plugin: "virtual_costmap_layer::VirtualLayer"
        enabled: True
        zone_topics: virtual_costamp_layer/zone
        obstacle_topics: virtual_costamp_layer/obsctacles
        one_zone: False     
        forms1: [0.4, 0.0]
        forms2: [[0.4, 0.0]]
        forms3: [[-0.4, 0.0],[0.0, 0.4]]
        forms4: [[5, 5],[-5, 5],[-5, -5],[5, -5]]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.58
        inflation_radius: 1.75
      always_send_full_costmap: True

map_server:
  ros__parameters:
    use_sim_time: False
    # Overridden in launch by the "map" launch configuration or provided default value.
    # To use in yaml, remove the default "map" value in the tb3_simulation_launch.py file & provide full path to map below.
    yaml_filename: ""

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

smoother_server:
  ros__parameters:
    use_sim_time: False
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    global_frame: odom
    robot_base_frame: base_footprint
    transform_tolerance: 0.1
    use_sim_time: False
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    use_sim_time: False
    loop_rate: 10
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    use_sim_time: False
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.26, 0.0, 1.0]
    min_velocity: [-0.26, 0.0, -1.0]
    max_accel: [2.5, 0.0, 3.2]
    max_decel: [-2.5, 0.0, -3.2]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0