sick_scan2: # configuration for sick_scan2_tim_5xx: For compatibility with ros versions previous to foxy, node and parameter name changed to sick_scan2 for all supported scanner. The type of scanner is configured by scanner_name only.
  ros__parameters:
    hostname : "192.168.0.1"
    frame_id : "laser" #"cloud"
    scanner_name : "sick_tim_5xx"
    port : 2112
    min_ang : -2.35619 #0.0 
    max_ang :  2.35619 #3.141 
    #max_range : 10.0 #in meters, for 551 and 561
    max_range : 25.0 #in meters, for 571
